# Application Configuration
server:
  port: 8080
  servlet:
    context-path: /business/police-management/v1
  error:
    include-message: always
    include-binding-errors: always

# DataSource Configuration
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/db_diviac
    username: postgres
    password: ${POSTGRES_PASS:securePassword123.}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 10000
      maxLifetime: 40000
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true
    lazy_initialization: true

# TODO: Define file size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    net.sf.jmimemagic.MagicParser: ERROR