--TABLA DE TABLAS GRUPO PARAMETRO
insert into generales.tb_grupo_parametro(
int_id_grupo, vch_cod_grupo, vch_desc_grupo, bol_estado)
VALUES 
(1, 'TP01', 'TABLA DE TIPO DE DIRECCION',TRUE),
(2, 'TP02', 'TABLA DE DOCUMENTO DE IDENTIDAD',TRUE),
(3, 'TP03', 'TABLA DE SITUACION DEL EFECTIVO',TRUE),
(4, 'TP04', 'TABLA DE ESTADO CIVIL',TRUE),
(5, 'TP05', 'TABLA DE SEXO',TRUE),
(6, 'TP06', 'TABLA DE CARGO DEL EFECTIVO',TRUE),
(7, 'TP07', 'TABLA DE ESPECIALIDAD DEL EFECTIVO',TRUE),	
(8, 'TP08', 'TABLA DE GRADO DEL EFECTIVO',TRUE),
(9, 'TP09', 'TABLA DE DOCUMENTOS INTELIGENCIA',TRUE),
(10, 'TP10', 'TABLA DE DOCUMENTOS DE INVESTIGACION',TRUE),
(11, 'TP11', 'TABLA ORGANIGRAMA OC',TRUE),
(12, 'TP12', 'TABLA REDES SOCIALES',TRUE),	
(13, 'TP13', 'TABLA CARACTERISTICAS FISICAS',TRUE),
(14, 'TP14', 'TABLA OPERADOR CELULAR',TRUE),
(15, 'TP15', 'TABLA TIPO DE VEHICULO',TRUE),	
(16, 'TP16', 'TABLA TIPO DE ARMA',TRUE),	
(17, 'TP17', 'TABLA TITULO DEL DELITO',TRUE),	
(128, 'TP128', 'TABLA VEHICULOS AEREOS',TRUE),
(129, 'TP129', 'TABLA VEHICULOS MARITIMO',TRUE),
(130, 'TP130', 'TABLA VEHICULOS TERRESTRE',TRUE),
(150,'TP150','DELITOS CONTRA LA VIDA, EL CUERPO Y LA SALUD',TRUE),
(151,'TP151','DELITOS CONTRA EL HONOR',TRUE),
(152,'TP152','DELITOS CONTRA LA FAMILIA',TRUE),
(153,'TP153','DELITOS CONTRA LA LIBERTAD',TRUE),
(154,'TP154','DELITOS CONTRA EL PATRIMONIO',TRUE),
(155,'TP155','DELITOS CONTRA LA CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS',TRUE),
(156,'TP156','DELITOS CONTRA LOS DERECHOS INTELECTUALES',TRUE),
(157,'TP157','DELITOS CONTRA EL PATRIMONIO CULTURAL',TRUE),
(158,'TP158','DELITOS CONTRA EL ORDEN ECONÓMICO',TRUE),
(159,'TP159','DELITOS CONTRA EL ORDEN FINANCIERO Y MONETARIO',TRUE),
(160,'TP160','DELITOS TRIBUTARIOS',TRUE),
(161,'TP161','DELITOS CONTRA LA SEGURIDAD PÚBLICA',TRUE),
(162,'TP162','DELITOS AMBIENTALES',TRUE),
(163,'TP163','DELITOS CONTRA LA SALUD PÚBLICA',TRUE),
(164,'TP164','DELITOS CONTRA LA HUMANIDAD',TRUE),
(165,'TP165','DELITOS CONTRA EL ESTADO Y LA DEFENSA NACIONAL',TRUE),
(166,'TP166','DELITOS CONTRA LOS PODERES DEL ESTADO Y ORDEN CONSTITUCIONAL',TRUE),
(167,'TP167','DELITOS CONTRA LA VOLUNTAD POPULAR',TRUE),
(168,'TP168','DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA',TRUE),
(169,'TP169','DELITOS CONTRA LA FE PÚBLICA',TRUE),
(170,'TP170','DELITOS CONTRA EL ORDEN MIGRATORIO',TRUE),
(171,'TP171','DELITOS CONTRA LA TRANQUILIDAD PÚBLICA',TRUE);


	

--TABLA DE TIPO DE DIRECCION
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(1,1,  'AVENIDA', TRUE),
(2,1,  'CALLE', TRUE),
(3,1,  'JIRÓN', TRUE),
(4,1,  'PASAJE', TRUE),
(5,1,  'C.P MENOR', TRUE),
(6,1,  'ANEXOS', TRUE),
(7,1,  'AAHH', TRUE),
(8,1,  'C.P MAYOR', TRUE),
(9,1,  'CASERIO', TRUE),
(10,1,  'OTROS', TRUE);


--TABLA DE DOCUMENTO DE IDENTIDAD
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(11,2,  'DNI', TRUE),
(12,2,  'LICENCIA DE CONDUCIR', TRUE),
(13,2,  'LIBRETA MILITAR', TRUE),
(14,2,  'PASAPORTE', TRUE),
(15,2,  'CARNET EXTRANJERIA', TRUE),
(16,2,  'CEDULA DE IDENTIDAD', TRUE),
(17,2,  'PTP -  PERMISO TEMPORAL DE PERMANECIA', TRUE),
(18,2,  'ANALISIS', TRUE);



--TABLA DE SITUACION DEL EFECTIVO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(19,3,  'VACACIONES', TRUE),
(20,3,  'PERMISO', TRUE),
(21,3,  'APOYO SUB UNIDAD', TRUE),
(22,3,  'COMISION', TRUE),
(23,3,  'LICENCIAS', TRUE),
(24,3,  'MATERNIDAD', TRUE),
(25,3,  'PATERNIDAD', TRUE),
(26,3,  'FALLECIMEINTO', TRUE),
(27,3,  'ADOPCION', TRUE),
(28,3,  'AISLADO POR COVID', TRUE),
(29,3,  'TRABAJO REMOTO', TRUE);

--tabla de estado civil
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(30,4, 'SOLTERO', TRUE),
(31,4,  'CASADO', TRUE),
(32,4,  'VIUDO', TRUE),
(33,4,  'CONVIVIENTE', TRUE),
(34,4,  'DIVORCIADO', TRUE);


--TABLA DE ORIENTACION SEXUAL
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(35,5, 'HOMBRE', TRUE),
(36,5,  'MUJER', TRUE);

--TABLA DE TIPO DE cargo del efectivo
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(37,6,  'JEFE DIVISION', TRUE),
(38,6,  'JEFE DEPARTAMENTO', TRUE),
(39,6,  'OFICIAL DE INTELIGENCIA', TRUE),
(40,6,  'OFICIAL DE INVESTIGACIONES', TRUE),
(41,6,  'AGENTE DE INTELIGENCIA', TRUE),
(42,6,  'ADMINISTRATIVO', TRUE),
(43,6,  'INVESTIGADOR', TRUE),
(44,6,  'DOCUMENTARIO', TRUE);

--TABLA DE TIPO DE especialidad del efectivo
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(45,7,  'INVESTIGACION', TRUE),
(46,7,  'ADMINISTRACION', TRUE),
(47,7,  'INTELIGENCIA', TRUE);

--TABLA DE grado del efectivo
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(48,8, 'TNTE GENERAL', TRUE),
(49,8,  'GENERAL', TRUE),
(50,8,  'GENERAL (S)', TRUE),
(51,8,  'CORONEL', TRUE),
(52,8,  'CORONEL (S)', TRUE),
(53,8, 'COMANDANTE', TRUE),
(54,8,  'COMANDANTE (S)', TRUE),
(55,8,  'MAYOR', TRUE),
(56,8,  'MAYOR (S)', TRUE),
(57,8,  'CAPITAN', TRUE),
(58,8, 'CAPITAN (S)', TRUE),
(59,8,  'TENIENTE', TRUE),
(60,8,  'ALFEREZ', TRUE),
(61,8,  'SUB OFICIAL SUPERIOR', TRUE),
(62,8,  'SUB OFICIAL SUPERIOR (S)', TRUE),
(63,8, 'SUB OFICIAL BRIGADIER', TRUE),
(64,8,  'SUB OFICIAL BRIGADIER (S)', TRUE),
(65,8,  'SUB OFICIAL TECNICO 1RA', TRUE),
(66,8,  'SUB OFICIAL TECNICO 1RA (S)', TRUE),
(67,8,  'SUB OFICIAL TECNICO 2DA', TRUE),
(68,8, 'SUB OFICIAL TECNICO 2DA (S)', TRUE),
(69,8,  'SUB OFICIAL TECNICO 3RA', TRUE),
(70,8,  'SUB OFICIAL TECNICO 3RA (S)', TRUE),
(71,8,  'SUB OFICIAL 1RA', TRUE),
(72,8,  'SUB OFICIAL 1RA (S)', TRUE),
(73,8, 'SUB OFICIAL 2DA', TRUE),
(74,8,  'SUB OFICIAL 2DA (S)', TRUE),
(75,8,  'SUB OFICIAL 3 RA', TRUE),
(76,8,  'SUB OFICIAL 3 RA (S)', TRUE);

--TABLA DE TIPO DE DOCUMENTOS INTELIGENCIA
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(77,9,  'PEDIDO DE INFORMACION', TRUE),
(78,9,  'ORDEN DE BUSQUEDA ', TRUE),
(79,9,  'NOTA DE AGENTE', TRUE),
(80,9,  'NOTA DE INFORMACIÓN', TRUE),
(81,9,  'APRECIACION', TRUE),
(82,9,  'INFORME', TRUE),
(83,9,  'NOTA DE INTELIGENCIA', TRUE);
 
--TABLA DE TIPO DE DOCUMENTOS DE INVESTIGACION
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(84,10,  'NOTIFICACION DE DETENCION', TRUE),
(85,10,  'INFORME', TRUE),
(86,10,  'PARTE POLICIAL', TRUE),
(87,10,  'ACTA', TRUE),
(88,10,  'OFICIO', TRUE),
(89,10,  'DECLARACION', TRUE),
(90,10,  'MANIFESTACION', TRUE),
(91,10,  'ENTREVISTA', TRUE),
(92,10,  'NOTA INFORMATIVA', TRUE),
(93,10,  'NOTIFICACION POLICIAL', TRUE),
(94,10,  'CONSTANCIA DETENCION', TRUE);


--TABLA DE TIPO DE especialidad del efectivo
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(95,11,  'LIDER/CABECILLA', TRUE),
(96,11,  'LUGARTENIENTE', TRUE),
(97,11,  'TESTAFERROS', TRUE),
(98,11,  'SICARIOS', TRUE),
(99,11,  'FINANCISTA', TRUE),
(100,11,  'BRAZO LEGAL', TRUE),
(101,11,  'SEGURIDAD', TRUE),
(102,11,  'BRAZO ARMADO', TRUE),
(103,11,  'EJECUTOR', TRUE),
(104,11,  'LOGISTICO', TRUE),
(105,11,  'PROVEEDORES', TRUE),
(106,11,  'FACILITADORES', TRUE),
(107,11,  'AUTORIDADES POLITICAS', TRUE),
(108,11,  'FUNCIONARIOS DE GOBIERNO', TRUE),
(109,11,  'POLICIAS', TRUE),
(110,11,  'MIITARES', TRUE),
(111,11,  'JUEZ', TRUE),
(112,11,  'FISCAL', TRUE);

--TABLA DE ORIENTACION SEXUAL
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(113,12, 'FACEBOOK', TRUE),
(114,12, 'TWITTER', TRUE),
(115,12, 'INSTAGRAM', TRUE),
(116,12, 'TIKTOK', TRUE),
(117,12, 'WHATSAPP', TRUE),
(118,12, 'OTROS', TRUE);

--TABLA DE ORIENTACION SEXUAL
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(119,13, 'TATUAJE', TRUE),
(120,13, 'CICATRIZ', TRUE),
(121,13, 'DISCAPACIDAD FISICA', TRUE),
(122,13, 'OTROS', TRUE);

insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(123,14, 'ENTEL', TRUE),
(124,14, 'CLARO', TRUE),
(125,14, 'MOVISTAR', TRUE),
(126,14, 'BITEL', TRUE),
(127,14, 'TELEFONIA SATELITAL', TRUE);

insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(128,15, 'AEREO', TRUE),
(129,15, 'MARITIMO', TRUE),
(130,15, 'TERRESTRE', TRUE);

insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(131,128, 'AVION', TRUE),
(132,128, 'AVIONETA', TRUE),
(133,128, 'HELICOPTERO', TRUE);

insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(137,130, 'CAMIONETA', TRUE),
(138,130, 'AUTOMOVIL', TRUE),
(139,130, 'MOTOCICLETA', TRUE),
(140,130, 'TRIMOTO', TRUE),
(141,130, 'CAMION', TRUE),
(142,130, 'OMNIBUS', TRUE),
(143,130, 'MAQUINARIA PESADA', TRUE);

--TABLA ARMAS
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(144,16, 'PISTOLA', TRUE),
(145,16, 'REVOLVER', TRUE),
(146,16, 'FUSIL', TRUE),
(147,16, 'ARMA BLANCA', TRUE),
(148,16, 'EXPLOSIVOS', TRUE),
(149,16, 'AMETRALLADORAS', TRUE);

--TABLA TITULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(150,17,'DELITOS CONTRA LA VIDA, EL CUERPO Y LA SALUD',TRUE),
(151,17,'DELITOS CONTRA EL HONOR',TRUE),
(152,17,'DELITOS CONTRA LA FAMILIA',TRUE),
(153,17,'DELITOS CONTRA LA LIBERTAD',TRUE),
(154,17,'DELITOS CONTRA EL PATRIMONIO',TRUE),
(155,17,'DELITOS CONTRA LA CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS',TRUE),
(156,17,'DELITOS CONTRA LOS DERECHOS INTELECTUALES',TRUE),
(157,17,'DELITOS CONTRA EL PATRIMONIO CULTURAL',TRUE),
(158,17,'DELITOS CONTRA EL ORDEN ECONÓMICO',TRUE),
(159,17,'DELITOS CONTRA EL ORDEN FINANCIERO Y MONETARIO',TRUE),
(160,17,'DELITOS TRIBUTARIOS',TRUE),
(161,17,'DELITOS CONTRA LA SEGURIDAD PÚBLICA',TRUE),
(162,17,'DELITOS AMBIENTALES',TRUE),
(163,17,'DELITOS CONTRA LA SALUD PÚBLICA',TRUE),
(164,17,'DELITOS CONTRA LA HUMANIDAD',TRUE),
(165,17,'DELITOS CONTRA EL ESTADO Y LA DEFENSA NACIONAL',TRUE),
(166,17,'DELITOS CONTRA LOS PODERES DEL ESTADO Y ORDEN CONSTITUCIONAL',TRUE),
(167,17,'DELITOS CONTRA LA VOLUNTAD POPULAR',TRUE),
(168,17,'DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA',TRUE),
(169,17,'DELITOS CONTRA LA FE PÚBLICA',TRUE),
(170,17,'DELITOS CONTRA EL ORDEN MIGRATORIO',TRUE),
(171,17,'DELITOS CONTRA LA TRANQUILIDAD PÚBLICA',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(172,150,'HOMICIDIO SIMPLE',TRUE),
(173,150,'PARRICIDIO',TRUE),
(174,150,'HOMICIDIO CALIFICADO',TRUE),
(175,150,'FEMINICIDIO',TRUE),
(176,150,'SICARIATO',TRUE),
(177,150,'ABORTO',TRUE),
(178,150,'LESIONES ',TRUE),
(179,150,'LESIONES GRAVES',TRUE),
(180,150,'LESIONES LEVES ',TRUE),
(181,150,'EXPOSICIÓN O ABANDONO PELIGROSOS',TRUE),
(182,150,'OMISIÓN DE SOCORRO',TRUE),
(183,150,'OMISIÓN DE AUXILIO',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(184,151,'INJURIA ',TRUE),
(185,151,'CALUMNIA',TRUE),
(186,151,'DIFAMACIÓN',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(187,152,'BIGAMIA ',TRUE),
(188,152,'MATRIMONIO CON PERSONA CASADA',TRUE),
(189,152,'AUTORIZACIÓN ILEGAL DE MATRIMONIO',TRUE),
(190,152,'ALTERACIÓN O SUPRESIÓN DEL ESTADO CIVIL',TRUE),
(191,152,'FINGIMIENTO DE EMBARAZO',TRUE),
(192,152,'ALTERACIÓN O SUPRESIÓN DE FILIACIÓN DE MENOS',TRUE),
(193,152,'SUSTRACCIÓN DE MENOR',TRUE),
(194,152,'INDUCCIÓN A LA FUGA DE MENOR',TRUE),
(195,152,'OMISIÓN DE PRSTACIÓN DE ALIMENTOS',TRUE),
(196,152,'ABANDONO DE MUJER GESTANTE',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(197,153,'COACCIÓN ',TRUE),
(198,153,'ACOSO',TRUE),
(199,153,'SECUESTRO',TRUE),
(200,153,'TRATA DE PERSONAS',TRUE),
(201,153,'EXPLOTACIÓN SEXUAL',TRUE),
(202,153,'EXCLAVITUD ',TRUE),
(203,153,'PROMOCIÓN O FAVORECIMIENTO DE EXPLOTACIÓN SEXUAL',TRUE),
(204,153,'CLIENTE DE LA EXPLOTACIÓN SEXUAL',TRUE),
(205,153,'BENEFICIO POR EXPLOTACIÓN SEXUAL',TRUE),
(206,153,'GESTIÓN DE LA EXPLOTACIÓN SEXUAL',TRUE),
(207,153,'EXPLOTACIÓN SEXUAL DE NIÑAS, NIÑOS Y ADOLESCENTES',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(208,154,'HURTO SIMPLE',TRUE),
(209,154,'HURTO AGRAVADO',TRUE),
(210,154,'HURTO DE USO',TRUE),
(211,154,'ROBO',TRUE),
(212,154,'ROBO AGRAVADO',TRUE),
(213,154,'ABIGEATO',TRUE),
(214,154,'APROPIACIÓN ILÍCITA',TRUE),
(215,154,'RECEPTACIÓN ',TRUE),
(216,154,'ESTAFAS',TRUE),
(217,154,'DEFRAUDACIÓN ',TRUE),
(218,154,'ADMINISTRACIÓN FRAUDULENTA',TRUE),
(219,154,'EXTORSIÓN ',TRUE),
(220,154,'CHANTAJE',TRUE),
(221,154,'USURPACIÓN ',TRUE),
(222,154,'DAÑOS',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(223,156,'COPIA O REPRODUCCIÓN NO AUTORIZADA',TRUE),
(224,156,'REPRODUCCIÓN, DIFUSIÓN, DISTRIBUCIÓN DE OBRA SIN AUTORIZACIÓN ',TRUE),
(225,156,'PLAGIO',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(226,157,'ATENTADO CONTRA MONUMENTOS ARQUEOLÓGICOS ',TRUE),
(227,157,'EXTRACCIÓN ILEGAL DE BIENES CULTURALES',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(228,158,'ABUSO DE PODER ECONÓMICO',TRUE),
(229,158,'ACAPARAMIENTO',TRUE),
(230,158,'ESPECULACIÓN ',TRUE),
(231,158,'ADULTERACIÓN ',TRUE),
(232,158,'VENTA ILÍCITA DE MERCADERÍAS',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(234,161,'DELITOS DE PELIGRO',TRUE),
(235,161,'FABRICACIÓN, SUMINISTRO O TENENCIA DE MATERIALES PELIGROSOS',TRUE),
(236,161,'PRODUCCIÓN, DESARROLLO Y COMERCIALIZACIÓN ILEGAL DE ARMAS QUÍMICAS ',TRUE),
(237,161,'SUSTRACCIÓN O ARREBATO DE ARMAS DE FUEGO',TRUE),
(238,161,'TRÁFICO DE PRODUCTOS PIROTÉCNICOS ',TRUE),
(239,161,'EMPLEO, PRODUCCIÓN DE MINAS PERSONALES',TRUE),
(240,161,'USO DE ARMAS EN ESTADO EBRIEDAD ',TRUE),
(241,161,'FABRICACIÓN, COMERCIALIZACIÓN DE ARMAS',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(242,162,'CONTAMINACIÓN DEL AMBIENTE',TRUE),
(243,162,'INCUMPLIMIENTO DE NORMAS RELATIVAS AL MANEJO DE RESIDUOS SÓLIDOS',TRUE),
(244,162,'TRÁFICO ILEGAL DE RESIDUOS PELIGROSOS',TRUE),
(245,162,'MINERÍA ILEGAL',TRUE),
(246,162,'FINANCIAMIENTO DE LA MINERÍA ILEGAL',TRUE),
(247,162,'OBSTACULIZACIÓN DE FISCALIZACIÓN ADMINISTRATIVA',TRUE),
(248,162,'TRÁFICO ILÍCITO DE INSUMOS QUÍMICOS Y MAQUINARIAS PARA LA MINERÍA ILEGAL',TRUE),
(249,162,'TRÁFICO ILEGAL DE FLORA Y FAUNA SILVESTRE',TRUE),
(250,162,'TRÁFICO ILEGAL DE ESPECIE ACUÁTICA DE FLORA Y FAUNA',TRUE),
(251,162,'EXTRACCIÓN Y PROCESAMIENTO ILEGAL DE ESPECIES ACUÁTICAS',TRUE),
(252,162,'DEPREDACIÓN DE FLORA Y FAUNA SILVESTRE',TRUE),
(253,162,'TRÁFICO ILEGAL DE RECURSOS GENÉTICOS',TRUE),
(254,162,'DELITO CONTRA BOSQUES Y FORMACIONES BOSCOSAS',TRUE),
(255,162,'TRÁFICO ILEGAL DE PRODUCTOS FORESTAL MADERABLE',TRUE),
(256,162,'OBSTRUCCIÓN DE PROCEDIMIENTO',TRUE),
(257,162,'UTILIZACIÓN INDEBIDA DE TIERRAS AGRÍCOLAS ',TRUE),
(258,162,'ALTERACIÓN DE AMBIENTE O PAISAJEPOR INFORMACIÓN FALSA',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(259,163,'CONTAMINACIÓN O ADULTERACIÓN DE BIENES O INSUMOS DENSTINADOS AL CONSUMO HUMANOS',TRUE),
(260,163,'CONTAMINACIÓN O ADULTERACIÓN DE ALIMENTOS O BEBIDAS',TRUE),
(261,163,'USO DE PRODUCTOS TOXICOS ILEGALES',TRUE),
(262,163,'PRODUCCIÓN DE ENFERMEDAD PELIGROSA O CONTAGIOSA',TRUE),
(263,163,'EJERCICIO ILEGAL DE LA MEDICINA',TRUE),
(264,163,'EJERCICIO MALICIOSO Y DESLEAL DE LA MEDICINA',TRUE),
(265,163,'VIOLACIÓN DE MEDIDAS SANITARIAS',TRUE),
(266,163,'VENTA DE ANIMALES DE CONSUMO PELIGROSOS',TRUE),
(267,163,'SUMINISTRO INFIEL DE PRODUCTOS FARMACEÚTICOS',TRUE),
(268,163,'FALSIFICACIÓN, CONTAMINACIÓN DE PRODUCTOS FARMACEÚTICOS',TRUE),
(269,163,'PROMOCIÓN O FAVORECIMIENTO DE TRÁFICO ILÍCITO DE DROGAS ',TRUE),
(270,163,'COMERCIALIZACIÓN Y CULTIVO DE AMAPOLA Y MARIHUANA',TRUE),
(271,163,'TRÁFICO DE INSUMOS QUÍMICOS ',TRUE),
(272,163,'MICROCOMERCIALIZACIÓN O MICROPRODUCCIÓN',TRUE),
(273,163,'SUMINISTRO INDEBIDO DE DROGA',TRUE),
(274,163,'COACCIÓN AL CONSUMO DE DROGA',TRUE),
(275,163,'INDUCCIÓN O INSTIGACIÓN AL CONSUMO DE DROGA.',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(276,164,'GENOCIDIO',TRUE),
(277,164,'DESAPARICIÓN FORZADA',TRUE),
(278,164,'TORTURA',TRUE),
(279,164,'MANIPULACIÓN GENÉTICA',TRUE),
(280,164,'DISCRIMINACIÓN',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(281,165,'ATENTADO CONTRA LA INTEGRIDAD NACIONAL',TRUE),
(282,165,'PARTICIPACIÓN EN GRUPO ARMADO DIRIGIDO POR EXTRANJERO',TRUE),
(283,165,'DESTRUCCIÓN O ALTERACIÓN DE HITOS FRONTERIZOS',TRUE),
(284,165,'INTELIGENCIA DESLEAL CON ESTADO EXTRANJERO',TRUE),
(285,165,'REVELACIÓN DE SECRETOS NACIONALES ',TRUE),
(286,165,'ESPIONAJE',TRUE),
(287,165,'FAVORECIMIENTO BÉLICO A ESTADO EXTRANJERO',TRUE),
(288,165,'PROVOCACIÓN PÚBLICA A LA DESOBEDIENCIA MILITAR',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(289,166,'REBELIÓN',TRUE),
(290,166,'SEDICIÓN ',TRUE),
(291,166,'MOTÍN',TRUE),
(292,166,'CONSPIRACIÓN PARA REBELIÓN, SEDICIÓN Y MOTÍN',TRUE),
(293,166,'SEDUCCIÓN, USURPACIÓN Y RETENCIÓN ILEGAL DE MANDO',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(294,167,'PERTURBACIÓN O IMPEDIMENTO DE PROCESO ELECTORAL',TRUE),
(295,167,'IMPEDIMENTO DEL EJERCICIO DE DERECHO DE SUFARGIO',TRUE),
(296,167,'INDUCCIÓN A NO VOTAR O HACERLO EN SENTIDO DETERMINADO',TRUE),
(297,167,'SUPLANTACIÓN DEL VOTANTE',TRUE),
(298,167,'PUBLICIDAD ILEGAL DEL SENTIDO DEL VOTO',TRUE),
(299,167,'ATENTADOS CONTRA EL DERECHO DE SUFRAGIO',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(300,168,'USURPACIÓN DE FUNCIONES',TRUE),
(301,168,'OSTENTACIÓN DE DISTINTIVOS DE FUNCIÓN O CARGO QUE NO EJERCE',TRUE),
(302,168,'EJERCICIO ILEGAL DE PROFESIÓN',TRUE),
(303,168,'VIOLENCIA CONTRA LA AUTORIDAD PARA IMPEDIR EL EJERCICIO DE SUS FUNCIONES',TRUE),
(304,168,'RESISTENCIA O DESOBEDIENCIA CONTRA LA AUTORIDAD',TRUE),
(305,168,'INGRESO INDEBIDO DE EQUIPOS EN INSTALACIÓN PENITENCIARIA ',TRUE),
(306,168,'SABOTAJE DE EQUIPOS DE SEGURIDAD',TRUE),
(307,168,'POSESIÓN INDEBIDA DE TELEFONOS CELULARES EN INSTALACIONES PENITENCIARIAS ',TRUE),
(308,168,'INGRESO INDEBIDO DE ARMAS A ESTABLECIMIENTO PENITENCIARIO',TRUE),
(309,168,'PERTURBACIÓN DEL ORDEN EN EL LUGAR DONDE LA AUTORIDAD EJERCE SU FUNCIÓN ',TRUE),
(310,168,'ABUSO DE AUTORIDAD',TRUE),
(311,168,'OTORGAMIENTO INDEBIDO DE DERECHOS SOBRE IMUEBLES ',TRUE),
(312,168,'OMISIÓN, REHUDAMIENTO DE ACTOS FUNCIONALES',TRUE),
(313,168,'DENEGACIÓN O DEFICIENTE APOYO POLICIAL',TRUE),
(314,168,'REQUERIMIENTO INDEBIDO DE LA FUERZA',TRUE),
(315,168,'ABANDONO DE CARGO',TRUE),
(316,168,'NOMBRAMIENTO O ACEPTACIÓN ILEGAL',TRUE),
(317,168,'CONCUSIÓN ',TRUE),
(318,168,'COBRO INDEBIDO',TRUE),
(319,168,'COLUSIÓN ',TRUE),
(320,168,'PATROCINIO ILEGAL',TRUE),
(321,168,'PECULADO',TRUE),
(322,168,'PECULADO DE USO',TRUE),
(323,168,'MALVERSACIÓN',TRUE),
(324,168,'RETARDO INJUSTIFICADO DE PAGO',TRUE),
(325,168,'REHUSAMIENTO A ENTREGA DE BIENES DEPOSITADOS O PUESTOS EN CUSTODIA',TRUE),
(326,168,'COHECHO PASIVO',TRUE),
(327,168,'SOBORNO INTERNACIONAL PASIVO',TRUE),
(328,168,'COHECHO PASIVO IMPROPIO',TRUE),
(329,168,'COHECHO PASIVO ESPECÍFICO',TRUE),
(330,168,'COECHO PASIVO PROPIO EN EL EJERCICIO DE FUNCIÓN POLICIAL',TRUE),
(331,168,'APROVECHAMIENTO INDEBIDO DEL CARGO',TRUE),
(332,168,'COHECHO ACTIVO GENÉRICO',TRUE),
(333,168,'COHECHO ACTIVO TRANSNACIONAL',TRUE),
(334,168,'COHECHO ACTIVO ESPECIFICO ',TRUE),
(335,168,'TRÁFICO DE INFLUENCIAS ',TRUE),
(336,168,'ENRIQUECIMIENTO ILÍCITO',TRUE),
(337,168,'DENUNCIA CALUMNIOSA',TRUE),
(338,168,'ENCUBRIMIENTO PERSONAL',TRUE),
(339,168,'ENCUBRIMIENTO REAL',TRUE),
(340,168,'OMISIÓN DE DENUNCIA',TRUE),
(341,168,'FALSEDAD EN JUICIO',TRUE),
(342,168,'OBSTRUCCIÓN DE JUSTICIA',TRUE),
(343,168,'AVOCAMIENTO ILEGAL A PROCESO EN TRÁMITE',TRUE),
(344,168,'EXPEDICIÓN DE PRUEBA O INFORMA FALSO EN PROCESO JUDICIAL',TRUE),
(345,168,'FAVORECIMIENTO A LA FIGA',TRUE),
(346,168,'FRAUDE PROCESAL',TRUE),
(347,168,'INSOLVENCIA PROVOCADA',TRUE),
(348,168,'PREVARICATO',TRUE),
(349,168,'DETENCIÓN ILEGAL',TRUE),
(350,168,'PROHIBICIÓN DE CONCOER PROCESO QUE SE PATROCINÓ',TRUE),
(351,168,'DENEGAICÓN Y RETARDO DE JUSTICIA',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(352,169,'FALSIFICACIÓN DE DOCUMENTOS',TRUE),
(353,169,'FALSEDAD IDEOLÓGICA',TRUE),
(354,169,'FALSEDAD EN EL REPORTE DE VOLÚMENES DE PESCA',TRUE),
(355,169,'OMISIÓN DE CONSIGNAR DECLARACIÓN EN DOCUMENTOS',TRUE),
(356,169,'SUPRESIÓN, DESTRUCCIÓN U OCULTAMIENTO DE DOCUMENTOS',TRUE),
(357,169,'EXPEDICIÓN DE CERTIFICADO MÉDICO FALSO',TRUE),
(358,169,'FALSIFICACIÓN DE SELLOS Y TIMBRES OFICIALES',TRUE),
(359,169,'FABRICACIÓN DE MARCAS O CONTRASEÑAS OFICIALES',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(360,170,'TRÁFICO ILÍCITO DE MIGRANTES',TRUE),
(361,170,'FORMAS AGRAVADAS',TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(362,171,'DISTURBIOS',TRUE),
(363,171,'DELITOS DE GRAVE PERTURBACIÓN DE LA TRANQUILIDAD PÚBLICA',TRUE),
(364,171,'APOLOGÍA',TRUE),
(365,171,'APOLOGÍA DEL DELITO DE TERRORISMO',TRUE),
(366,171,'ORGANIZACIÓN CRIMINAL',TRUE),
(367,171,'MARCAJE O REGLAJE',TRUE),
(368,171,'BANDA CRIMINAL',TRUE),
(369,171,'OFENSA A LA MEMORIA DE LOS MUERTOS',TRUE),
(370,171,'INTERMEDIACIÓN ONEROSA DE ORGANOS',TRUE);

insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES 
(371,129, 'CONTENEDORES', TRUE),
(372,129, 'BOTE', TRUE),
(373,129, 'LANCHA', TRUE),
(374,129, 'YATE', TRUE),
(375,129, 'MORO ACUATICA', TRUE),
(376,129, 'EMBARCACIONES PESQUERAS', TRUE),
(377,129, 'BARCOS', TRUE);

--TABLA ARTICULO DEL DELITO
insert into generales.tb_parametro(
int_id_parametro,int_id_grupo,  vch_desc_parametro, bol_estado)
VALUES
(378,159,'CONCENTRACIÓN CREDITICIA',TRUE),
(379,159,'OCULTAMIENTO, OMISIÓN O FALSEDAD DE INFORMACIÓN',TRUE),
(380,159,'FALSEDAD DE INFORMACIÓN PRESENTADA POR UN EMISOR',TRUE),
(381,159,'INSTITUCIONES FINANCIERAS ILEGALES ',TRUE),
(382,159,'FINANCIAMIENTO POR MEDIO DE INFORMACIÓN FRAUDULENTA',TRUE),
(383,159,'CONDICIONAMIENTO DE CRÉDITOS ',TRUE),
(384,159,'PANICO FINANCIERO',TRUE);
