server:
  port: 8080
  servlet:
    context-path: /channel/administration-management/v1
  error:
    include-message: always
    include-binding-errors: always

feign:
  client:
    config:
      business-division-api:
        base-url: http://${BUSINESS_DIVISION_API_HOST:localhost}:${BUSINESS_DIVISION_API_PORT:8080}/business/division-management/v1/divisions
        connectTimeout: 25000
        readTimeout: 30000
        writeTimeout: 25000
        loggerLevel: basic